### ISSUE TITLE
CVPR 2023 

### ISSUE THREAD

**Issue by jshilong** [mindgarage-shan/transformer_object_detection_survey#1]
Thank you for your compilation and summary. You may consider adding 
https://openaccess.thecvf.com/content/CVPR2023/html/Zhang_Dense_Distinct_Query_for_End-to-End_Object_Detection_CVPR_2023_paper.html

Thanks

**Comment by khurramHashmi** [comment]
Hello Shilong,

Thanks for the useful contribution. This paper has been added now.

In the future, please feel free to create a pull request.
